apiVersion: v1
kind: Pod
metadata:
  name: csv-queue-producer
spec:
  restartPolicy: Never
  containers:
    - name: csv-queue-producer
      image: eduardpredescu/csv-producer:1.0
      ports:
        - containerPort: 8081
      env:
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: csv-queue-producer
spec:
  selector:
    app: csv-queue-producer
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer
