#--- deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-crawler
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-crawler
  serviceName: web-crawler-headless
  template:
    metadata:
      labels:
        app: web-crawler
    spec:
      containers:
        - name: app
          image: eduardpredescu/web-crawler:1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: CLUSTER_NODES
              value: elasticsearch:9300
            - name: CLUSTER_HOST
              value: elasticsearch
            - name: REST_URI
              value: elasticsearch:9200
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

  volumeClaimTemplates:
    - metadata:
        name: shared-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: web-crawler-headless
spec:
  selector:
    app: web-crawler
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
